// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt_Esti_Frederik.Models;

public partial class Class
{
    [Key]
    [Column("ClassID")]
    public int ClassId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string ClassName { get; set; }

    [InverseProperty("Class")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}