// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt_Esti_Frederik.Models;

public partial class Designation
{
    [Key]
    [Column("DesignationID")]
    public int DesignationId { get; set; }

    [Column("TeacherID")]
    public int? TeacherId { get; set; }

    public int? ExamId { get; set; }

    //there should not be a single student for a designation as this is meant for teachers.
    //public int StudentId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string DesignationRole { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("Designations")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("TeacherId")]
    [InverseProperty("Designations")]
    public virtual Teacher Teacher { get; set; }
}