// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt_Esti_Frederik.Models;

public partial class Exam
{
    [Key]
    [Column("ExamID")]
    public int ExamId { get; set; }

    [Column("ClassID")]
    public int? ClassId { get; set; }


    public int DesignationId {  get; set; } 
    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string ExamName { get; set; }

    public int EstimatedNumberStudents { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string TypeOfExam { get; set; }

    public bool Supervision { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TypeOfSupervisor { get; set; }

    public DateOnly ExamSubmissionDate { get; set; }

    public DateOnly ExamDate { get; set; }

    public TimeOnly ExamStartTime { get; set; }

    public TimeOnly ExamEndTime { get; set; }

    public DateOnly ReExamSubmissionDate { get; set; }

    public DateOnly ReExamDate { get; set; }

    public TimeOnly ReExamStartTime { get; set; }

    public TimeOnly ReExamEndTime { get; set; }

    [ForeignKey("ClassId")]
    [InverseProperty("Exams")]
    public virtual Class Class { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Designation> Designations { get; set; } = new List<Designation>();
}