// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Projekt_Esti_Frederik.Models;

public partial class ExamPlannerDBContext : DbContext
{
    public ExamPlannerDBContext()
    {
    }

    public ExamPlannerDBContext(DbContextOptions<ExamPlannerDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Designation> Designations { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=mssql15.unoeuro.com;Initial Catalog=buggo_dk_db_exam_planner_db;User ID=buggo_dk;Password=Rxmdc5efthzE2D4A3rGp;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False;Command Timeout=30");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Class>(entity =>
        {
            entity.HasKey(e => e.ClassId).HasName("PK__Classes__CB1927A067F87701");
        });

        modelBuilder.Entity<Designation>(entity =>
        {
            entity.HasKey(e => e.DesignationId).HasName("PK__Designat__BABD603EE1AEF492");

            entity.HasOne(d => d.Exam).WithMany(p => p.Designations).HasConstraintName("FK__Designati__ExamI__66603565");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Designations).HasConstraintName("FK__Designati__Teach__656C112C");
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.ExamId).HasName("PK__Exams__297521A7E384A9C2");

            entity.HasOne(d => d.Class).WithMany(p => p.Exams).HasConstraintName("FK__Exams__ClassID__5BE2A6F2");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.TeacherId).HasName("PK__Teachers__EDF25944DC773D6B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}